# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port for dev server
EXPOSE 3000

# Start dev server with hot reload
CMD ["npm", "start"]
