FROM node:20-alpine

WORKDIR /app

# Install dependencies early for cache efficiency
COPY package.json package-lock.json ./
RUN npm ci

# Copy rest of the files
COPY . .

# Expose the port React dev server uses (default 3000)
EXPOSE 3000

# Start React dev server
CMD ["npm", "start"]
